server:
  port: 0
spring:
  application:
    name: secKill-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.26.177.51:3306/haibing?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000

  cloud:
    nacos:
      discovery:
        #        server-addr: 120.26.177.51:8848
        server-addr: localhost:8848
        #        namespace: ef32c1be-c63c-4db4-8b07-b3b84a7c27ef

        metadata:
          instance: cc
          version: 1.0
          author: tt

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        content-center:
          loggerLevel: full
          requestInterceptors:
            - com.soft.seckillcenter.feignclient.TokenInterceptor

  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

ribbon:
  eager-load:
    enabled: true
    clients: content-center

content-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

