server:
  port: 8813
spring:
  application:
    name: mq-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0

  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

        metadata:
          instance: cc
          version: 1.0
          author: tt

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        content-center:
          loggerLevel: full
          requestInterceptors:
            - com.soft.mqcenter.feignclient.TokenInterceptor

  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

ribbon:
  eager-load:
    enabled: true
    clients: content-center

content-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

