server:
  port: 8082
spring:
  application:
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.26.177.51:3306/haibing?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: userhaibing
    password: passhaibing
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
#    host: 120.26.177.51
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
    timeout: 5000

  cloud:
    nacos:
      discovery:
        #        server-addr: 120.26.177.51:8848
        server-addr: localhost:8848
        #        namespace: ef32c1be-c63c-4db4-8b07-b3b84a7c27ef

        metadata:
          instance: cc
          version: 1.0
          author: tt

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#rocketmq:
#  name-server: 47.111.64.183:9876
#  name-server: 120.26.177.51:9876

