export const ACCESS_TOKEN = 'Access-Token'
export const USER_PHONE = 'Login_User_Phone'
export const USER_INFO = 'Login_UserInfo'
export const USER_ID = 'Login_UserId'
export const USER_AVATAR = 'Login_Avatar'